version: "3.9"

services:
  db:
    image: postgres:17.2
    container_name: db
    networks:
      - main
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./postgres.env
    ports:
      - "5432:5432"
    restart: always

  service_1:
    build:
      context: ./services/service_1
      dockerfile: Dockerfile
    image: service_1:1.0
    container_name: service_1
    volumes:
      - ./services/service_1:/app/
      - static:/app/static
      - media:/app/media
    networks:
      - main
    depends_on:
      - db
    env_file:
      - ./services/service_1/.env
    ports:
      - "8001:8000"
    restart: always

  service_2:
    build:
      context: ./services/service_2
      dockerfile: Dockerfile
    image: service_2:1.0
    container_name: service_2
    volumes:
      - ./services/service_2:/app/
      - static:/app/static
      - media:/app/media
    networks:
      - main
    depends_on:
      - db
    env_file:
      - ./services/service_2/.env
    ports:
      - "8002:8000"
    restart: always

  nginx:
    image: nginx:1.27.3
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - static:/var/www/static
      - media:/var/www/media
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - main
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
  static:
  media:


networks:
  main:
